runtimes:
  - python@3.12.11

tools:
  - ruff@0.12.7
  - bandit@1.8.3
  - lizard@1.22.2
  - opengrep@1.21.0
  - pylint@4.0.5
  - trivy@0.70.0

exclude_paths:
  - "deprecated/**"
  - "docs/archive/**"
